// Project
export const ADDED_PROJECT_SUCCESS = 'ADDED_PROJECT_SUCCESS';
export const UPDATED_PROJECT_SUCCESS = 'UPDATED_PROJECT_SUCCESS';
export const FETCHED_PROJECT_SUCCESS = 'FETCHED_PROJECT_SUCCESS';
export const REMOVED_PROJECT_SUCCESS = 'REMOVED_PROJECT_SUCCESS';

// Task
export const ADDED_TASK_SUCCESS = 'ADDED TASK SUCCESS';
export const UPDATED_TASK_SUCCESS = 'UPDATED TASK SUCCESS';
export const FETCHED_TASK_SUCCESS = 'FETCHED TASK SUCCESS';
export const REMOVED_TASK_SUCCESS = 'REMOVED TASK SUCCESS';

//Auth
export const CREATED_USER_SUCCESS = 'CREATED USER SUCCESS';
export const LOGGED_USER_SUCCESS = 'LOGGED USER SUCCESS';
export const NO_USER_FOUND = 'AUTHENTICATION FAILED,  NO USER FOUND!';
export const WRONG_PASSWORD = 'AUTHENTICATION FAILED,  WRONG PASSWORD!';
export const SIGN_IN = 'SIGNIN';
export const UNAUTHORIZED_USER = "UNAUTHORIZED USER"
